### ISSUE TITLE
Cambios urgentes en front-end

### ISSUE THREAD

**Issue by JuanPabloF1609** [tjhoan/projectDesarrollo#12]
Se necesitan hacer cambios de ultima hora en las partes graficas, como logos, titulos en la zona de administración, entre otros.

**Comment by tjhoan** [comment]
Todos los cambios solicitados en las partes gráficas, incluyendo logos, títulos y la zona de administración, han sido implementados exitosamente. El front-end se encuentra actualizado según los requerimientos planteados. Gracias por el apoyo al equipo. Procedo a cerrar este issue.
