### ISSUE TITLE
Concretización de contenedores, imagenes, pruebas unitarias y de integraión en Docker

### ISSUE THREAD

**Issue by JuanPabloF1609** [tjhoan/projectDesarrollo#3]
Se es necesario solucionar y observar problemas si los hay y, confirmar la creación de contenedores e imágenes necesarias para la funcionalidad y continuidad del proyecto, además agregar el entorno de pruebas unitarias y de integración.

-Mysql
-php...

**Comment by tjhoan** [comment]
El problema ha sido solucionado. Toda la dockerización del proyecto, incluyendo la configuración de contenedores, imágenes y pruebas unitarias/integración, se ha finalizado exitosamente. El entorno ahora está completamente funcional y operativo. Gracias a todos los involucrados por su colaboración. Procedo a cerrar este issue.
