### ISSUE TITLE
Testing: Docker y codigo y uso de linter

### ISSUE THREAD

**Issue by JuanPabloF1609** [tjhoan/projectDesarrollo#4]
Se necesitan seguir las pruebas de nuevas unidades y crear el ambiente de pruebas en docker. También es necesario inspeccionar el código utilizando linter

**Comment by Santiago-090** [comment]
`[[Pruebas de linter.txt](https://github.com/user-attachments/files/18032958/Pruebas.de.linter.txt)
Se ha subido las pruebas de linter para el proyecto completo, en este caso PHP Sniffer
